### ISSUE TITLE
Why do we need spread operator and array in the config?

### ISSUE THREAD

**Issue by anchan42** [mbezhanov/laravel-faker-provider-collection#10]
Why do we need array here?

    ...(class_exists($class=Bezhanov\Faker\Laravel\FakerServiceProvider::class) ? [$class] : [])

Can we do? 
     class_exists($class = Bezhanov\Faker\Laravel\FakerServiceProvider::class) ? $class:null,

**Comment by mbezhanov** [comment]
Hi @anchan42,

The spread operator is certainly redundant in this example. This was an oversight in my end, and I just corrected the README file to reflect this.

You can find the latest README file published in version [3.0.1](https://github.com/mbezhanov/laravel-faker-provider-collection/tree/3.0.1).

Thanks a lot for pointing this out, and for helping keep the project clean!

**Comment by mbezhanov** [comment]
Hi again @anchan42 ,

I just reverted the example in the README file to its old variant, where the suggested solution is to use a spread operator:

```php
...(class_exists($class=Bezhanov\Faker\Laravel\FakerServiceProvider::class) ? [$class] : [])
```

When you originally opened this issue, I couldn't get an error with  the code you suggested:

```php
class_exists($class = Bezhanov\Faker\Laravel\FakerServiceProvider::class) ? $class : null,
````

Therefore, I thought there was an oversight on my end and updated the `README` file in the repo accordingly. However, I was wrong. I wasn't getting any errors, because my test script kept calling `composer install` instead of `composer install --no-dev` and I didn't notice that earlier.

The issue with the code you suggested occurs when you run `composer install --no-dev`.

In such occasions, Laravel outputs the following error:

```text
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In ProviderRepository.php line 206:

Class name must be a valid object or a string  

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

If you try modifying this to:

```php
class_exists($class = Bezhanov\Faker\Laravel\FakerServiceProvider::class) ? $class : '',
```

This also results in an error:

```text
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In ProviderRepository.php line 206:

Class "" not found  

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

But if you use the spread operator example:

```php
...(class_exists($class=Bezhanov\Faker\Laravel\FakerServiceProvider::class) ? [$class] : [])
```

Everything completes successfully.

I have therefore reverted the `README` file example to its previous version.

This has been published as version [3.0.2](https://github.com/mbezhanov/laravel-faker-provider-collection/releases/tag/3.0.2)

**Comment by mbezhanov** [comment]
Hi once again @anchan42 :slightly_smiling_face: 

As you know, Laravel 11 got released about a week ago and certain changes have been applied to make it easier to register service providers with the application.

It is now enough to add the FakerServiceProvider class to your `./bootstrap/providers.php` file as follows:

```php
return [
    // other provider definitions
    Bezhanov\Faker\Laravel\FakerServiceProvider::class,
];
```

No spread operators and no ternary expressions are necessary, as the framework automatically executes `class_exists` during its bootstrap phase and skips any provider classes that do not exist.

This has been documented and published in [3.1.0](https://github.com/mbezhanov/laravel-faker-provider-collection/releases/tag/3.1.0)

**Comment by anchan42** [comment]
Thanks a lot for having a look at this. 🙏
composer install --no-dev could cause some packages not to be installed hence the error about the missing class?

**Comment by mbezhanov** [comment]
Yes, correct. The `--no-dev` flag skips the installation of development packages in order to optimize the size of the application for production deployment. Development packages are useful when working on the application locally, but not required for serving production traffic.
